# Generated by Django 6.0.7 on 2026-07-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_publishedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
