# Generated by Django 6.0.7 on 2026-07-19 14:30

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_processedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.user_directory_path),
        ),
    ]
