version: '3.8'

networks:
  microservice-network:
    driver: bridge
  
volumes:
  admin_postgres_data: {}
  user_postgres_data: {}
  kafka_data: {}
  minio-data: {}

services:
  # =======================================================
  # API GATEWAY (The Only Public Entry Point)
  # =======================================================
  api_gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - admin-service
    networks:
      - microservice-network
  
  # =======================================================
  # SHARED INFRASTRUCTURE (shared across all services)
  # =======================================================
  redis:
    image: redis:7-alpine
    container_name: shared_redis
    ports:
      - 6379:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - microservice-network
  
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-local
    ports:
      - "9092:9092"
    environment:
      # --- ADD OR UPDATE THESE PROPERTIES ---
      KAFKA_BROKER_MAX_NODE_TO_CONTROLLER_REQUEST_TIMEOUT_MS: 15000
      KAFKA_REQUEST_TIMEOUT_MS: 15000
      KAFKA_CONNECTION_MAX_IDLE_MS: 30000
      # If using KRaft mode explicitly, ensure these are generous:
      KAFKA_CONTROLLER_QUORUM_FETCH_TIMEOUT_MS: 15000
      KAFKA_CONTROLLER_QUORUM_ELECTION_TIMEOUT_MS: 15000

      KAFKA_OPTS: "-Xms512M -Xmx512M"
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
      # Enable KRaft mode (no ZooKeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      
      # Configure listeners for both inside Docker and your local host machine
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      
      # Automatically create topics if they don't exist yet
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      
      # Required cluster ID for KRaft mode
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      # Speed up message handling for local development
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      # Verifies Kafka is fully listening and accepting socket metadata handshakes
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - microservice-network

  minio:
    image: minio/minio:latest
    ports:
     - "9000:9000" # minio api port
     - "9001:9001" # minio web console port
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - microservice-network

  # =======================================================
  # ADMIN SERVICE MICROSTACK
  # =======================================================
  admin-postgres:
    image: postgres:16-alpine
    container_name: admin_postgres
    restart: always
    environment:
      POSTGRES_DB: admin_postgres_db   
      POSTGRES_USER: admin      
      POSTGRES_PASSWORD: admin_postgress_secure_password
    ports:
      - "5433:5432"
    volumes:
      - admin_postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - microservice-network
  
  admin-service:
    build:
      context: ./admin_service
      dockerfile: Dockerfile
    container_name: admin_app
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./admin_service:/app
    ports:
      - 8001:8001
    depends_on:
      - admin-postgres
    env_file:
      - ./admin_service/.env
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    networks:
      - microservice-network

  admin-worker:
    build:
      context: ./admin_service
      dockerfile: Dockerfile
    container_name: admin_app_worker
    command: python manage.py kafka_consumer
    volumes:
      - ./admin_service:/app
    depends_on:
      admin-postgres:
        condition: service_started
      kafka:
        condition: service_healthy
    env_file:
      - ./admin_service/.env
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    networks:
      - microservice-network
  
  admin-celery-worker:
    build:
      context: ./admin_service
      dockerfile: Dockerfile
    container_name: admin_app_celery_worker
    command: celery -A core worker --loglevel=info --concurrency=1 --without-mingle --without-gossip -Ofair
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - ./admin_service/.env
    environment:
      - REDIS_URL=redis://shared_redis:6379/0
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    restart: always
    networks:
      - microservice-network
  
  admin-celery-beats:
    build:
      context: ./admin_service
      dockerfile: Dockerfile
    container_name: admin_app_celery_beat
    command: celery -A core beat -l info
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./admin_service/.env
    environment:
      - REDIS_URL=redis://shared_redis:6379/0
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    restart: always
    networks:
      - microservice-network
  
  # =======================================================
  # USER SERVICE MICROSTACK
  # =======================================================
  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./init-minio.sh:/init-minio.sh
    entrypoint: ["/bin/sh", "/init-minio.sh"]
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin123
      BUCKET_NAME: django-media
    networks:
      - microservice-network

  user-postgres:
    image: postgres:16-alpine
    container_name: user_postgres
    restart: always
    environment:
      POSTGRES_DB: user_postgres_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_postgress_secure_password
    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - microservice-network

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_app
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - ./user_service:/app
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_healthy   # Wait until redis-cli ping succeeds
      user-postgres:
        condition: service_started
    env_file:
      - ./user_service/.env
    environment:
      - REDIS_URL=redis://shared_redis:6379/2
      - ADMIN_MICROSERVICE_URL=http://admin-service:8001
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
      - MINIO_STORAGE_ENDPOINT=minio:9000
      - MINIO_STORAGE_ACCESS_KEY=minioadmin
      - MINIO_STORAGE_SECRET_KEY=minioadmin123
      - MINIO_STORAGE_BUCKET_NAME=django-media
    networks:
      - microservice-network

  user-worker:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_app_worker
    command: python manage.py kafka_consumer
    volumes:
      - ./user_service:/app
    depends_on:
      user-postgres:
        condition: service_started
      kafka:
        condition: service_healthy
    env_file:
      - ./user_service/.env
    environment:
      - REDIS_URL=redis://shared_redis:6379/2
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    networks:
      - microservice-network
  
  user-celery-worker:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_app_celery_worker
    command: celery -A core worker --loglevel=info --concurrency=1 --without-mingle --without-gossip -Ofair
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - ./user_service/.env
    environment:
      - REDIS_URL=redis://shared_redis:6379/1
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    restart: always
    networks:
      - microservice-network
  
  user-celery-beats:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_app_celery_beats
    command: celery -A core beat -l info
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./user_service/.env
    environment:
      - REDIS_URL=redis://shared_redis:6379/1
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    restart: always
    networks:
      - microservice-network
