version: '3.8'

services:  
  audit-service:
    build:
      context: ./audit_service
      dockerfile: Dockerfile
    container_name: audit_app
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./audit_service:/app
    ports:
      - 8002:8002
    depends_on:
      audit-mongodb:
        condition: service_healthy
    env_file:
      - ./audit_service/.env
    environment:
      - MONGODB_URL=mongodb://root:securepassword123@audit-mongodb:27017/      
  
  audit-mongodb:
    image: mongo:4.4
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017" 
    environment:
      # old env variable name for mongo-4.4
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: securepassword123
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    
  audit-worker:
    build:
      context: ./audit_service
      dockerfile: Dockerfile
    container_name: audit_app_worker
    command: python manage.py kafka_consumer
    volumes:
      - ./audit_service:/app
    env_file:
      - ./audit_service/.env
    environment:
      - MONGODB_URL=mongodb://root:securepassword123@audit-mongodb:27017/
    depends_on:
      audit-mongodb:
        condition: service_healthy

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:securepassword123@audit-mongodb:27017/
    depends_on:
      audit-mongodb:
        condition: service_healthy
  
volumes:
  mongo_data: