# Generated by Django 6.0.7 on 2026-07-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminApplicationReviewStatus',
        ),
        migrations.AlterField(
            model_name='adminapplicationreview',
            name='review_status',
            field=models.CharField(choices=[('new_application', 'New Application'), ('under_review', 'Under Review'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new_application', max_length=20),
        ),
    ]
