# Generated by Django 6.0.7 on 2026-07-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_delete_adminapplicationreviewstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('is_consumed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='adminapplicationreview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposting'),
        ),
    ]
