# Generated by Django 6.0.7 on 2026-07-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_processedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminapplicationreview',
            name='resume_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
